// <auto-generated />
namespace BikeMates.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Migration31aug : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migration31aug));
        
        string IMigrationMetadata.Id
        {
            get { return "201508311243138_Migration31aug"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
